name: Check

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:

jobs:
  check:
    uses: stormreply/slt-workflows/.github/workflows/check.yaml@main
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
      STORM_LIBRARY_FOR_TERRAFORM: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
      TERRAFORM_PRIVATE_KEY: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
